si446xcfg.so: si446xcfg.c si446x.h radio_platform_si446x.h radio_config_si446x.h Si446xLocalConfig.h
	gcc -o si446xcfg.so -shared -fPIC -I/usr/include/python2.7 -lpython2.7 si446xcfg.c
	cp si446xcfg.so ..

